# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [1]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [7]:
A = np.arange(1, 16).reshape(3,5)
print("Dimension:", A.ndim)
print("Shape:", A.shape)
print("Size:", A.size)
print("Datatype:", A.dtype)

Dimension: 2
Shape: (3, 5)
Size: 15
Datatype: int64


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [21]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2
print('This is matris B')
print(B)
print('This is matris C')
print(C)
print('Elemntwise subtraction B-C')
print(B - C)
print('Elementwise multiplication B*C ')
print(B * C)
print('Matrix multiplication B@C by default @')
print(B @ C)

This is matris B
[[1 2 3]
 [4 5 6]
 [7 8 9]]
This is matris C
[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]
Elemntwise subtraction B-C
[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]
Elementwise multiplication B*C 
[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]
Matrix multiplication B@C by default @
[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [47]:
import numpy as np
# skapa matrisen B
B = np.arange(1, 10).reshape(3, 3)
print("Matrix B:")
print(B)

Matrix B:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [49]:
#Exponentiate each number elementwise
exp_B = np.exp(B)
print("\nExponentierade värden (np.exp):")
print(exp_B)


Exponentierade värden (np.exp):
[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]


In [51]:
# Minimumvärde i hela matrisen
min_value = np.min(B)
print("\nMinimumvärde i hela matrisen:", min_value)


Minimumvärde i hela matrisen: 1


In [55]:
# Minimumvärde i varje rad
min_value_row = np.min(B, axis=1)
print("Minimumvärde i varje rad:", min_value_row)

Minimumvärde i varje rad: [1 4 7]


In [59]:
# Minimumvärde i varje kolumn
min_value_col = np.min(B, axis=0)
print("Minimumvärde i varje kolumn:", min_value_col)

Minimumvärde i varje kolumn: [1 2 3]


In [61]:
# Index för minimumvärdet i hela matrisen
min_index = np.argmin(B)
print("\nIndex för minimumvärdet i hela matrisen:", min_index)


Index för minimumvärdet i hela matrisen: 0


In [63]:
# Index för minimumvärdet i varje rad
min_index_row = np.argmin(B, axis=1)
print("\nIndex för minimumvärdet i hela matrisen:", min_index)


Index för minimumvärdet i hela matrisen: 0


In [65]:
# Summera alla element
sum_elements = np.sum(B)
print("\nSumma av alla element:", sum_elements)


Summa av alla element: 45


In [67]:
# Medelvärde för varje kolumn
mean_col = np.mean(B, axis=0)
print("Medelvärde för varje kolumn:", mean_col)

Medelvärde för varje kolumn: [4. 5. 6.]


In [69]:
# Median för varje kolumn
median_col = np.median(B, axis=0)
print("Median för varje kolumn:", median_col)

Median för varje kolumn: [4. 5. 6.]


### What does it mean when you provide fewer indices than axes when slicing? See example below.


In [77]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
The history saving thread hit an unexpected error (OperationalError('attempt to write a readonly database')).History will not be written to the database.


In [79]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:**
När man gör en slicing som A[1], betyder det att man vill ha den andra raden
Index 1 motsvara andra raden i matrisen (första raden har index 0), eftersom man skrev ingen index för kolumn, så tolkar NumPy att man vill ta med alla element i de axlar som inte är angivna, dvs, alla element av alla kolumner på den andra raden. 
Resultatet blir därför hela den andra raden

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [94]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [96]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


**Answer:**
Koden ovanför itererar först genom raderna i A och sedan genom varje element i de raderna.

### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [108]:
a = np.arange(30) #Den skapar en !D array med 30 heltal som startar med 0 och slutar med 29
b = a.reshape((2, 3, -1)) # funktion Reshape ändrar shape till array a (2 är storlek av första axeln, 3 storlek av andra axeln och 
                          # och -1 betyder att NumPy beräknar automatiskt storleken på axeln
print("Här är a")
print(a)
print("Här är b")
print(b)

Här är a
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
Här är b
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


**Answer:**

"a = np.arange(30)" - Den skapar en !D array med 30 heltal som startar med 0 och slutar med 29
"b = a.reshape((2, 3, -1))"funktion Reshape ändrar shape till array a (2 är storlek av första axeln, 3 storlek av andra axeln och -1 betyder att NumPy beräknar automatiskt storleken på axeln

b har två block:
block 1 som representerar index 0 innehåller 3 rader och 5 kolumner och visar tal från 0 till 14
block 2 representerar index 1, innehåller 3 rader och 5 kolumner och visar tal från 15 till 29

Sammanfattning:
a är en endimensionell array, 1D-array, med 30 element
b är en 3D-array med formen (2, 3, 5), vilket innebär att den har 2 block, 3 rader och 5 kolumner per rad
-1 i reshape gör att NumPy automatiskt beräknar storleken på den sista axeln (här som 5) baserat på de andra axlarnas storlekar och det totala antalet element.



# For the exercises below, read the document *"matematik_yh_antonio_vektorer_matriser_utdrag"*
# Solutions to the exercises and recorded videos can be found here: https://github.com/AntonioPrgomet/matematik_foer_yh

# If you find the exercises below very hard, do not worry. Try your best, that will be enough. 

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [119]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
#print(m1 + m2)

if m1.shape == m2.shape:
    print(m1 + m2)
else:
    print("Matrices have different shapes and cannot be added.")

Matrices have different shapes and cannot be added.


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [121]:
v1 = np.array([1, 2, 3])
print(v1)
print(v1 + 1)

[1 2 3]
[2 3 4]


**Answer:**
v1 är en endimensionell vektor med 3 elementer (1D-array)
Här, NumPy adderar automatiskt 1 för varje element i vektoren. 
#[1+1, 2+1, 3+1] = [2, 3, 4]

Alltså, detta fungerar så, eftersom broadcasting gör att skalären 1 appliceras elementsvis på vektor v1

In [123]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


**Answer:**
Koden A=np.arange(1,5).reshape(2,2) skapar en 1D-array (endimentionell vektor) med siffrona från 1 till 4
och .reshape(2,2) omformar den till en 2x2 matris.
[[1 2]
 [3, 4]]

 np.array([2,2]) skapar en 1D-array(vektor) med två element [2, 2]

 Sammanfattning:

 Brodcasting gör att skalär 1 läggs till varje element i den vektoren v1

 Man kan skapa en 2D-matris genom att omforma en 1D-array är en giltig operation inom NumPy och behöver ingen broadcastin, bara omformning

 Alltså, matris- och vektoroperationer i Python kan följa broadcasting-reglerna vilket skiljer sig från matematiska reglerna inom linjär algebra. 

 Broadcast gör att operationer mellan vektorer med olika former kan fungera så länge de kan justeras enligt vissa regler, som t.ex en skalär kan läggas till vektorer med olika dimensioner.

# Vector- and matrix algebra Exercises

**Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.**

**Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In [136]:
import numpy as np

def add_mult_matrices(m1, m2, operation):
    # Validate that m1 and m2 are numpy.ndarray
    if not isinstance(m1, np.ndarray) or not isinstance(m2, np.ndarray):
        raise ValueError("Both input matrices must be of type numpy.ndarray")
    
    # Validate that the operation is either 'add' or 'multiply'
    if operation not in ['add', 'multiply']:
        raise ValueError("The operation must be either 'add' or 'multiply'")
    
    # Perform addition
    if operation == 'add':
        # Check if the matrices have the same shape
        if m1.shape != m2.shape:
            raise ValueError("Matrices must have the same shape for addition")
        return m1 + m2
    
    # Perform multiplication
    elif operation == 'multiply':
        # Check if multiplication is possible (columns of m1 == rows of m2)
        if m1.shape[1] != m2.shape[0]:
            raise ValueError("The number of columns in the first matrix must equal the number of rows in the second matrix")
        return np.dot(m1, m2)


In [150]:
#exempel 
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
#print("Addition of m1 and m2:")
#print(add_mult_matrices(m1, m2, 'add'))

print("Multiplication of m1 and m2:")
print(add_mult_matrices(m1, m2, 'multiply'))


Multiplication of m1 and m2:
[3 7]


### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan". 

In [218]:
import numpy as np
x = np.array([4, 3])

#a) Vilka dimension har vektorn x?
print ("a)", f"Dimension of x:{x.shape}")

#b) Calculate 5x
five_x = 5 * x
print ("b)", f"5x:{five_x}")

#c) Calculate 3x
three_x = 3 * x
print("c)", f"3x:{three_x}")

#d) Calculate 5x + 3x
result_5x_3x = five_x + three_x
print("d)", f"5x + 3x:{result_5x_3x}")

#e) Calculate 8x
eight_x = 8 *x
print("e)", f"8x : {eight_x}")

#f) Calculate 4x - x
result_4x_x = (4*x) - x
print("f)", f" 4x - x: {result_4x_x}")

#g) Calculate X^T (Transpose of x)
x_transpose = x.reshape(-1, 1)
print("g)", f"x^T: {x_transpose}")

#h) Is x + x^T definierat? Calculate |x|
try:
    x_plus_x_transpose = x + x_transpose
except ValueError:
    x_plus_x_transpose = "Not defined"

print("h)", f"x + x^T: {x_plus_x_transpose}")

# i) Calculate normalisering x
norm_x = np.linalg.norm(x)
print("i)", f"||x||: {norm_x}")

a) Dimension of x:(2,)
b) 5x:[20 15]
c) 3x:[12  9]
d) 5x + 3x:[32 24]
e) 8x : [32 24]
f)  4x - x: [12  9]
g) x^T: [[4]
 [3]]
h) x + x^T: [[8 7]
 [7 6]]
i) ||x||: 5.0


In [236]:
#Exercise 10.1.2  Define the vector v

v = np.array([3, 7, 0, 11])
print (v)

#a) Dimension of v
print("a)", f"Dimension of v: {v.shape}")

#b) Calculate 2v
two_v = 2 * v
print("b)", f"2v: {two_v}")

#c) Calculate 5v + 2v
result_5v_2v = (5*v) - two_v
print("c)", f"5v + 2v: {result_5v_2v}")

#d) Calculate 4v - 2v
result_4v_2v = (4*v) - two_v
print("d)", f"4v - 2v: {result_4v_2v}")

# (e) Calculate v^T (transpose of v)
v_transpose = v.reshape(-1, 1)
print("e)", f"v^T: {v_transpose}")

# (f) Calculate ||v||
norm_v = np.linalg.norm(v)
print("f)", f"||v||: {norm_v}")

[ 3  7  0 11]
a) Dimension of v: (4,)
b) 2v: [ 6 14  0 22]
c) 5v + 2v: [ 9 21  0 33]
d) 4v - 2v: [ 6 14  0 22]
e) v^T: [[ 3]
 [ 7]
 [ 0]
 [11]]
f) ||v||: 13.379088160259652


In [240]:
# Exercise 10.1.3: Define the vectors v1 and v2
v1 = np.array([4, 3, 1, 5])
v2 = np.array([2, 3, 1, 1])

# (a) Calculate ||v1||
norm_v1 = np.linalg.norm(v1)
print("a)", f"||v1||: {norm_v1}")

# (b) Calculate ||v1 - v2||
v1_minus_v2 = v1 - v2
norm_v1_minus_v2 = np.linalg.norm(v1_minus_v2)
print("b", f"||v1 - v2||: {norm_v1_minus_v2}")

a) ||v1||: 7.14142842854285
b ||v1 - v2||: 4.47213595499958


### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan". 

In [246]:
import numpy as np

# Define the matrices
A = np.array([[2, 1, -1], [1, -1, 1]])
B = np.array([[4, -2, 1], [2, -4, -2]])
C = np.array([[1, 2], [2, 1]])
D = np.array([[3, 4], [4, 3]])
E = np.array([[1], [2]])
I = np.array([[1, 0], [0, 1]])

# (a) Calculate 2A
two_A = 2 * A

# (b) Calculate B - 2A
B_minus_two_A = B - 2 * A

# (c) Calculate 3C - 2E
three_C = 3 * C
two_E = 2 * E
three_C_minus_two_E = three_C - two_E

# (d) Calculate 2D - 3C
two_D = 2 * D
three_C = 3 * C
two_D_minus_three_C = two_D - three_C

# (e) Calculate D^T + 2D
D_transpose = D.T
two_D = 2 * D
D_transpose_plus_two_D = D_transpose + two_D

# (f) Calculate 2C^T - 2D^T
C_transpose = C.T
D_transpose = D.T
two_C_transpose = 2 * C_transpose
two_D_transpose = 2 * D_transpose
two_C_transpose_minus_two_D_transpose = two_C_transpose - two_D_transpose

# (g) Calculate A^T - B (not defined if dimensions don't match)
A_transpose = A.T
try:
    A_transpose_minus_B = A_transpose - B
except ValueError:
    A_transpose_minus_B = "Not defined"

# (h) Calculate AC (this operation will be skipped due to dimension mismatch)
AC = "Not defined due to shape mismatch"

# (i) Calculate CD
try:
    CD = np.dot(C, D)
except ValueError:
    CD = "Not defined due to shape mismatch"

# (j) Calculate CB
try:
    CB = np.dot(C, B)
except ValueError:
    CB = "Not defined due to shape mismatch"

# (k) Calculate CI
CI = np.dot(C, I)

# Output the results
two_A, B_minus_two_A, three_C_minus_two_E, two_D_minus_three_C, D_transpose_plus_two_D, two_C_transpose_minus_two_D_transpose, A_transpose_minus_B, AC, CD, CB, CI


(array([[ 4,  2, -2],
        [ 2, -2,  2]]),
 array([[ 0, -4,  3],
        [ 0, -2, -4]]),
 array([[ 1,  4],
        [ 2, -1]]),
 array([[3, 2],
        [2, 3]]),
 array([[ 9, 12],
        [12,  9]]),
 array([[-4, -4],
        [-4, -4]]),
 'Not defined',
 'Not defined due to shape mismatch',
 array([[11, 10],
        [10, 11]]),
 array([[  8, -10,  -3],
        [ 10,  -8,   0]]),
 array([[1, 2],
        [2, 1]]))

### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [270]:
v1 = np.arange(4)
v2 = v1[-2:]
print("v1:", v1)
print("v2:", v2)

v1: [0 1 2 3]
v2: [2 3]
True
v1 after modifying v2: [  0   1   2 123]
v2 after modification: [  2 123]


In [272]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

#Since v1 is the original array, it does not have a base, therefore its output is None
#Since v2 is a view of v1, it returns the original array [0 1 2 3 ]

#another way to verify if the v1 and v2 are views or copies is to write following code:

#check if v1 and v2 are views or copies:
print(np.shares_memory(v1, v2)) # It will return True or False, in this case True because they are views.

None
[  0   1   2 123]
True


In [274]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
#modify the last element of v2:
v2[-1] = 123
print("v1 after modifying v2:", v1)
print("v2 after modification:", v2)


v1 after modifying v2: [  0   1   2 123]
v2 after modification: [  2 123]


**Answer:**
basic indexing creates often a view of the original array
v1 = np.arrange(4) creates a 1D-array som slutar innan fyra, it menas v1 = [0, 1, 2, 3]

v2 is a view of v1 because slicing creates a view by defaut, it means that we change v2, we can affect v1

Since v2 is a view of v1, when we changed v2[-1] till 123 modified also v1, in this case 123 is the last element of v2
